# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Jupyter Development Team
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: '@jupyter/sql-cell'
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension to run SQL in notebook dedicated
    cells
python_name: jupyter_sql_cell
repository: https://github.com/QuantStack/jupyter-sql-cell
test: true
viewer_name: ''

